name: Deploy Fullstack to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'sensor-api-go/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy-backend:
    name: Deploy backend (Go) to Elastic Beanstalk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sensor-api-go
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o app ./cmd/main.go

      - name: Ensure Procfile is present
        run: |
          if [ ! -f Procfile ]; then
            echo "web: ./app" > Procfile
          fi

      - name: Zip deploy files
        run: |
          zip -r deploy.zip app Procfile

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "Saas IM"
          environment_name: Saasim-prod-env
          region: us-east-2
          version_label: v-${{ github.sha }}
          deployment_package: sensor-api-go/deploy.zip

  deploy-frontend:
    name: Deploy frontend to S3
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies with retry
        run: |
          n=0
          until [ $n -ge 3 ]
          do
            npm install && break
            n=$((n+1))
            echo "npm install failed, retrying in 5s..."
            sleep 5
          done

      - name: Build frontend
        run: npm run build

      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: saas-im-frontend
          AWS_REGION: us-east-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: ./frontend/dist
