name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # O la rama que uses para producci贸n

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajusta a tu regi贸n

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "Saas IM"              # El nombre de tu aplicaci贸n
          environment_name: "SaasIM-env"           # El nombre del entorno en Beanstalk
          version_label: ${{ github.sha }}
          region: us-east-1                        # Ajusta a tu regi贸n
